name: Move Issue to In Progress

on:
  issues:
    types: [labeled, assigned]

permissions:
  issues: write
  contents: write # <-- Corrected permission

jobs:
  move_issue:
    runs-on: ubuntu-latest
    if: github.event.issue.pull_request == null
    steps:
      - name: Check if issue is assigned
        id: check_issue
        uses: actions/github-script@v6
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const isAssigned = context.payload.issue.assignee !== null;
            console.log("Is assigned:", isAssigned);
            return { moveIssue: isAssigned };

      - name: Move issue to 'In Progress' if assigned
        if: steps.check_issue.outputs.moveIssue == 'true'
        uses: actions/github-script@v6
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const projectNumber = 16; // <-- Replace PROJECT_NUMBER with your project number
            const repoName = context.repo.repo;
            const owner = context.repo.owner;
            const issueNumber = context.payload.issue.number;

            const projects = await github.projects.listForRepo({
              owner: owner,
              repo: repoName
            });
            const projectId = projects.data.find(proj => proj.number === projectNumber).id;
            console.log("Project ID:", projectId);

            const columns = await github.projects.listColumns({
              project_id: projectId
            });
            const backlogsColumn = columns.data.find(col => col.name === 'Backlogs'); // <-- Ensure 'Backlogs' matches your column name
            const inProgressColumn = columns.data.find(col => col.name === 'In Progress'); // <-- Ensure 'In Progress' matches your column name
            console.log("Backlogs Column ID:", backlogsColumn.id, "In Progress Column ID:", inProgressColumn.id);

            const card = await github.projects.listCards({
              column_id: backlogsColumn.id
            }).then(cards => cards.data.find(card => card.content_url.endsWith(issueNumber.toString())));

            if (card) {
              console.log("Card found:", card.id);
              await github.projects.moveCard({
                card_id: card.id,
                column_id: inProgressColumn.id,
                position: 'top'
              });
              console.log("Card moved to In Progress.");
            } else {
              console.log("Card not found in Backlogs column.");
            }
