name: Move Issue to In Progress

on:
  issues:
    types: [assigned]

jobs:
  move-card:
    runs-on: ubuntu-latest
    steps:
      - name: Move issue to "In Progress" column
        uses: peter-evans/project-card@v2
        with:
          project: 'demo'
          column: 'In Progress'
          github_token: ${{ secrets.NewToken }}
