name: Move card

on:
  # refer https://docs.github.com/en/actions/learn-github-actions/events-that-trigger-workflows#issues
  issues:
    types: [assigned]
  # refer https://docs.github.com/en/actions/learn-github-actions/events-that-trigger-workflows#issue_comment
  issue_comment:
    types: [created]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: ineshbose/project-card-action@v1
        with:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          ISSUE_NUMBER: ${{ github.event.issue.number }}
          TARGET_COLUMN: 'In Progress'
