name: automation for global projects
on:
  issues:
    types:
      - assigned

jobs:
  clear-inprogress-column:
    runs-on: ubuntu-latest
    steps:
      - uses: HiromiShikata/gh-actions-move-all-cards-on-projects@v1.0.2
        with:
          project_name: 202106
          from_column_name: In progress
          to_column_name: To do
          github_token: ${{ secrets.GITHUB_TOKEN }}
