on:
  issues:
    types: [assigned]
 
jobs:
  automate-issues-labels:
    runs-on: ubuntu-latest
    steps:
      - name: Move to In Progress
        uses: bishalrai96/Project_Card_Automation@master
        with:
          repo-token: "${{ secrets.GITHUB_TOKEN }}"
          column: "In Progress"
