name: Move Issue to In Progress

on:
  issues:
    types: [assigned]

jobs:
  move-card:
    runs-on: ubuntu-latest
    steps:
      - name: Move card to "In Progress"
        run: |
          ISSUE_URL="https://api.github.com/repos/${{ github.repository }}/issues/${{ github.event.issue.number }}/projects"
          PROJECT_ID="16"
          COLUMN_ID="278829"
          
          curl -X POST -H "Authorization: token ${{ secrets.NewToken }}" \
          -d "{\"project_id\": \"$PROJECT_ID\", \"column_id\": \"$COLUMN_ID\"}" \
          $ISSUE_URL
        env:
          GITHUB_TOKEN: ${{ secrets.NewToken }}
